extends Node


enum {
    CELL_CLOSED = 0,
    CELL_OPENED = 1,
}

const MAX_CELLS_COUNT: int = 36
const MAX_COLUMN: int = 6
const MAX_ROW: int = 6

var cell_data: PoolIntArray = [
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
    CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED, CELL_OPENED,
]
var cells_node: Node2D


func _ready() -> void:
    cells_node = get_parent()
